### ISSUE TITLE
Bad stack trace on JIT compilation failure from JITted code

### ISSUE THREAD

**Issue by aviansie-ben** [wasmjit-omr/wasmjit-omr#135]
It appears that the stack trace given if a function fails to JIT compile when being called from JITted code has an extraneous extra frame in it. Take the following simple module for instance:

```wasm
(module
  (memory 0)
  (func $f (result i32)
    memory.size)

  (func $g (result i32)
    call $f)

  (func (export "test") (result i32)
    call $g))
```

The function `$f` should fail to JIT compile since the `memory.size` opcode is not supported by the JIT compiler. However, the calling function `$g` will JIT compile successfully. Running this with the `--trap-on-failed-comp` option enabled results in the following stack trace:

```
test() => error: failed JIT compilation
  at test [@24]
  at $g [@20]
  at test [@32]
```

Note the extra call frame on the top of the stack trace. If `$g` were run in the interpreter, the following call stack would instead be printed:

```
test() => error: failed JIT compilation
  at $g [@20]
  at test [@32]
```

This problem is caused by two separate factors. The presence of the extra call frame is caused by the fact that we push our return address onto the call stack _before_ attempting the JIT compile. Additionally, the top frame appears to be in an entirely unrelated function due to the PC being stale at this point in time.

However, I'm considering slightly adjusting the stack trace given for failed JIT compiles to aid in debugging. The following stack trace might be better, as it gives more information about what function actually caused the issue:

```
test() => error: failed JIT compilation
  at $f [@0]
  at $g [@20]
  at test [@32]
```

@Leonardo2718 Thoughts?

**Comment by Leonardo2718** [comment]
Hm... I like the idea of showing what function caused the problem. We should document this behaviour thoroughly, though, to make it clear that the top function never actually got to run. Ideally, we would have a better way of just showing which failed to JIT compiler, but that would likely require more work. I think what you've proposed is a good compromise.
