### ISSUE TITLE
Implement i32 arithmetic opcodes

### ISSUE THREAD

**Issue by aviansie-ben** [wasmjit-omr/wasmjit-omr#33]
The following basic i32 arithmetic opcodes should be supported:

- `i32.add`
- `i32.sub`
- `i32.mul`
- `i32.div_s`
- `i32.rem_s`

The `i32.div_u` and `i32.rem_u` are being left until later due to JitBuilder's lack of an unsigned divide operation.

**Comment by mstoodle** [comment]
@aviansie-ben It wouldn't be hard to add unsigned div and rem if you find you need them. Just ping me ( @Leonardo2718 is fully capable to do it too, but I'm happy to help out with JitBuilder work to support you so you don't get distracted from your project).
